# Generated by Django 2.2.7 on 2020-01-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_people_good'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='good',
            field=models.ManyToManyField(to='catalog.Good'),
        ),
    ]
