# Generated by Django 2.2.7 on 2020-01-11 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_people_good'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='good',
        ),
    ]
