# Generated by Django 2.2.7 on 2020-01-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_people_good'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='people',
            field=models.ManyToManyField(to='catalog.People'),
        ),
    ]
