# Generated by Django 2.2.7 on 2020-01-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200111_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='good',
            field=models.ManyToManyField(to='catalog.Good'),
        ),
    ]
