# Generated by Django 2.2.7 on 2020-01-11 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20200111_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersPeople',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Good')),
                ('people', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.People')),
            ],
        ),
    ]
