# Generated by Django 2.2.7 on 2020-01-11 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_orderspeople'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='good',
        ),
        migrations.AddField(
            model_name='order',
            name='good',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Good'),
        ),
        migrations.DeleteModel(
            name='OrdersPeople',
        ),
    ]
