# Generated by Django 2.2.7 on 2020-01-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20200111_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='good',
        ),
        migrations.AddField(
            model_name='good',
            name='people',
            field=models.ManyToManyField(to='catalog.People'),
        ),
    ]
