# Generated by Django 2.2.7 on 2020-01-11 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_remove_order_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='people',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.People'),
        ),
        migrations.AddField(
            model_name='people',
            name='good',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Good'),
        ),
    ]
