# Generated by Django 2.2.7 on 2020-01-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20200111_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='good',
        ),
        migrations.AddField(
            model_name='people',
            name='good',
            field=models.ManyToManyField(to='catalog.Good'),
        ),
    ]
