# Generated by Django 2.2.7 on 2020-01-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_maincategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='photo',
            field=models.ImageField(default=1, upload_to='image'),
            preserve_default=False,
        ),
    ]
