# Generated by Django 2.2.7 on 2020-01-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_category_maincategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='maincategory',
        ),
        migrations.AddField(
            model_name='maincategory',
            name='category',
            field=models.ManyToManyField(null=True, to='catalog.Category'),
        ),
    ]
