# Generated by Django 2.2.7 on 2020-01-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_auto_20200120_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincategory',
            name='category',
            field=models.ManyToManyField(to='catalog.Category'),
        ),
    ]
